### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Kirbo** [flatlogic/awesome-bootstrap-checkbox#1]
Don't know should I post this issue here or for https://github.com/nghuuphuoc/bootstrapvalidator but either ways, these two don't work together, atleast not for me.

**1st improvement**:

``` css
.checkbox input[type=radio],
.checkbox input[type=checkbox] {
        position: absolute;
        left: -1000px;
}
```

I think using this method instead of **display: none;** is better, but correct me if I'm wrong. _Atleast in my case, this made bootstrapValidator validate my checkboxes/radiobuttons also._

**2nd "improvement"**:
_This should probably be reported for bootstrapValidator, instead of here?_
I had change every sibling selectors from + into ~ to make this work (not the best possible way to make it work though):

``` css
...
...
.checkbox input[type=checkbox]:checked ~ label:after {
    font-family: 'FontAwesome';
    content: "\f00c"; }
.checkbox input[type=checkbox]:disabled ~ label {
    opacity: 0.65; }
.checkbox input[type=checkbox]:disabled ~ label:before {
    background-color: #eeeeee;
...
...
```

Reason why I had to do this change is because bootstrapValidator places feedback icons (**<i>**) immediately after <input> elements:

``` html
<div class="form-group has-feedback">
  <div class="col-sm-8 col-sm-offset-3">
    <div class="checkbox">
      <input type="checkbox" name="terms" id="terms" value="1" required="" data-bv-field="terms" />
      <i class="form-control-feedback" data-bv-field="terms" style="display: none;"></i>
      <label for="terms">I accept the terms of use</label>
    </div>
  <small data-bv-validator="notEmpty" class="help-block" style="display: none;">You must accept the terms of use</small></div>
</div>
```

Anyway, keep up the good work :+1: :)
