### ISSUE TITLE
Usage with FontAwesome v5

### ISSUE THREAD

**Issue by lucianomilen** [flatlogic/awesome-bootstrap-checkbox#137]
It seems that using the awesome-bootstrap-checkbox won't work with the newest version of FontAwesome, since there's no `font-family` property to set the icon's `content`. Are you planning on upgrading this component to use FontAwesome v5?

**Comment by NightMan-1** [comment]
Hi!

Try this:

```css
.abc-checkbox input[type="checkbox"]:checked + label::after,
.abc-checkbox input[type="radio"]:checked + label::after {
  font-family: "Font Awesome 5 Pro", "Font Awesome 5 Free", "FontAwesome";
  content: "\f00c"; }
```

ps I use Font Awesome 5 Pro

**Comment by ellenhutchings** [comment]
Using less to set the font family to "Font Awesome 5 Free" still leaves it not working.

The font-weight, also needs to be overridden to be 900 (at least for the free version). Based on my checking, as low as 600 will also work, but why complicate things.

This should either be changed in the project, or added as a variable for less/sass users (or both)

**Comment by Xen3r0** [comment]
Hi,

Could be working with awesome-boostrap-checkbox 0.3.7 ?

I try:
```css
.checkbox input[type="checkbox"]:checked + label::after,
.checkbox input[type="radio"]:checked + label::after {
  font-family: "Font Awesome 5 Free";
  content: "\f00c";
}

input[type="checkbox"].styled:checked + label:after,
input[type="radio"].styled:checked + label:after {
  font-family: "Font Awesome 5 Free";
  content: "\f00c";
}
```

But doesn't work :(

**Comment by ellenhutchings** [comment]
The font-weight needs to be 900

**Comment by htrex** [comment]
I'm using Font Awesome 5 and importing the fa-check icon with the following code on app.module.ts 
```
import {faCheck} from '@fortawesome/fontawesome-free-solid';
fontawesome.library.add(faCheck);
```
The icon is shown without problem using a classic HTML tag in the templates of any component, even lazy loaded ones.
```<span class="fas fa-check"></span>```

... but Font Awesome 5 for Angular uses JS and SVG internally instead of a font, so the suggested workaround doesn't fix the problem in this case.

At the end I've used https://icomoon.io to export just the fa-check icon in a font, imported that and changed the above workaround to use my single icon font.

**Comment by ellenhutchings** [comment]
You can use web fonts with font awesome. The package has the fonts and css in the web-fonts-with-css folder.

**Comment by lucianomilen** [comment]
I tried @NightMan-1 's solution but it didn't work. I was on AngularJS btw... Strangely the plugin works perfectly on Angular5 :thinking:

**Comment by HunterLomo** [comment]
But doesn't work ,too  :(

**Comment by EgorZotov** [comment]
This helped me to restore checkbox. 

**In CSS**
```css 
.abc-checkbox input[type="checkbox"]:checked+label::after,
.abc-checkbox input[type="radio"]:checked+label::after {
    font-family: "Font Awesome 5 Pro", "Font Awesome 5 Free";
    content: "\f00c";
    font-weight: 900;
}
```

**In HTML**
``` html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
```
