### ISSUE TITLE
Checkbox without label

### ISSUE THREAD

**Issue by lazabogdan** [flatlogic/awesome-bootstrap-checkbox#17]
Would be nice to support single controls without displaying the label (useful for checkboxes in tables for example).

Here's what I used:

```css
.checkbox.checkbox-single {
	label {
		width: 0;
		height: 16px;
		visibility: hidden;
		&:before, &:after {
			visibility: visible;
		}
	}
}
```
