### ISSUE TITLE
Possible to remove blue glow?

### ISSUE THREAD

**Issue by emertechie** [flatlogic/awesome-bootstrap-checkbox#31]
I'm trying to remove the blue glow on a focused checkbox but nothing is working so far. I'm trying something like:

```css
#checkbox1:focus {
  outline: 0px !important;
  -webkit-appearance:none !important;

  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  box-shadow: none !important;
}
```

But I still get the glow. Any suggestions?

Thanks

**Comment by emertechie** [comment]
Ah, misunderstanding of how the effect is created. For anyone else, you need to style the label::before pseudoelement like so:

```css
.checkbox input[type="checkbox"]:focus + label::before {
  outline: none;
}
```
