### ISSUE TITLE
Vertical align middle

### ISSUE THREAD

**Issue by 11digitlabs** [flatlogic/awesome-bootstrap-checkbox#37]
Aligning vertically in the middle does not seem to work, no matter what I've tried.
Any suggestions are appreciated

Thanks!

**Comment by DimaSavchenko** [comment]
You can give the screen? So we can better understand your problem.

**Comment by elmalto** [comment]
Running into the same issue: The vertical alignment of text is off

![Image of Alignment issue]
(http://s9.postimg.org/io92nv567/ALBHZi_NDe3n_EIXL9_Ow_LEFSUBx_I4_Djpv3h_Vt_LNRn74c.png)

**Comment by tvdeyen** [comment]
If the `line-height` is higher then normal, the vertical alignment is broken:
 
<img width="390" alt="brand eins kiosk - brand eins kiosk 2016-02-05 15-15-44" src="https://cloud.githubusercontent.com/assets/42868/12848608/57e137c0-cc1b-11e5-9085-d750a87185ff.png">

This is because of the `position: absolute` of the `label::before` and `after` elements.

This fixes it:

```sass
@import "awesome-bootstrap-checkbox";

.radio, .checkbox {

  label {

    &::before, &::after { top: 50%; }
    &::before { margin-top: -9px; }
    &::after { margin-top: -6px; }
  }
}
```

**Comment by mahendhar9** [comment]
Thank you @tvdeyen, it works!

**Comment by LeiChat** [comment]
I've added the fix @tvdeyen advised which aligned the label text with the box, thank you, but I have some issues with the location of the tick. I'm using Bootstrap v3.3.7

![capture1](https://cloud.githubusercontent.com/assets/23559551/26827548/bb7d1fbe-4ab5-11e7-9694-c199b9437eec.PNG)

**Comment by mrdnote** [comment]
I'm having the same problem as @LeiChat

**Comment by LeiChat** [comment]
For the .radio label before and after classes I have used margin-top: 3px, rather than the -9px and -6px that @tvdeyen suggested.

**Comment by iYalovoy** [comment]
Any solutions for pure css?

**Comment by th2062** [comment]
Pure css: 
```
.radio label::before, .checkbox label::before, .radio label::after, .checkbox label::after {
  top: 50%;
}
.radio label::before, .checkbox label::before {
  margin-top: -9px;
}
.radio label::after, .checkbox label::after {
  margin-top: -6px;
}
```
In the future, you can use http://www.cssportal.com/scss-to-css/

**Comment by alexanderpepper** [comment]
Using the answer provided by @tvdeyen, here's a pure CSS solution that also solves the issue @LeiChat identified:

```css
.radio label::before,
.checkbox label::before,
.radio label::after,
.checkbox label::after {
    top: 50%;
}

.radio label::before,
.checkbox label::before {
    margin-top: -9px;
}

.radio label::after {
    margin-top: -6px;
}

.checkbox label::after {
    margin-top: -9px;
}
```
