### ISSUE TITLE
Add Bootstrap 2.x support/branch

### ISSUE THREAD

**Issue by Hyperc0der** [flatlogic/awesome-bootstrap-checkbox#43]
I have some project with Bootstrap 2.3.x. So I was required to change this lines to make it works:

```css
.checkbox label::after {
    left: 1px;
    top: -1px;
}
```
```css
.radio label::after {
    left: 4px;
    top: 4px;
}
```

Maybe there's another workaround?
