### ISSUE TITLE
Font Awesome not necessary

### ISSUE THREAD

**Issue by yamass** [flatlogic/awesome-bootstrap-checkbox#51]
I use awesome-bootstrap-checkbox **without font-awesome** (I actually use bootstrap's glyphicon font instead) and I think this might be interesting for others. As far as I can see awesome-bootstrap-checkbox uses only one (!) icon from font-awesome.

I simply add the following to my less code **after** the `@import` of awesome-bootstrap-checkbox:

```less
@import "../bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.less";

@font-family-icon: 'Glyphicons Halflings';
@fa-var-check: "\e013";

.checkbox label::after {
  font-size: 10px;
}
```
Maybe you could add this to the documentation or even add some kind of configuration option for choosing the icon font.
