### ISSUE TITLE
Focus state broke with bootstrap v3.3.7

### ISSUE THREAD

**Issue by xt0rted** [flatlogic/awesome-bootstrap-checkbox#98]
I'm using the less version in my project and after updating to v3.3.7 of bootstrap the focus state broke and I'm no longer getting the dotted line around the controls. This is a result of the `.tab-focus()` mixin being changed in https://github.com/twbs/bootstrap/pull/20275

For now I'm doing the following to fix this.

``` less
@import "bootstrap/bootstrap.less";
.tab-focus()
{
    outline: thin dotted;
    outline: 5px auto -webkit-focus-ring-color;
    outline-offset: -2px;
}
@import "../bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.less";
```
